POST http://localhost:5000/api/auth/session
Content-Type: application/json

{
    "username": "hackthesouth",
    "password": "123htn456"
}

###
GET http://localhost:5000/api/users/test
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySUQiOiIxNDM1MDkiLCJ1c2VybmFtZSI6ImhhY2t0aGVzb3V0aCIsImV4cCI6MTYzMTQ3NDgzNX0.BGaZL-Nr6WBa_UDgNuuElrUi_DQh6UKZL3G3qvd7B8c

###
PUT http://localhost:5000/api/auth/session

###
DELETE http://localhost:5000/api/auth/session