name: Jest E2E
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test-client
